// BlueprintGeneratedClass MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C
// Size: 0x28 (Inherited: 0x28)
struct UMadnessGameplayAbilityFunctionLibrary_C : UBlueprintFunctionLibrary {

	void AddDamageAndImpulse(struct AActor* DamageCauser, struct AController* Instigator, struct UMadBlastBaseComponent* Target, struct FCollisionShapeBPWrapper CollisionShape, struct FVector Origin, struct FQuat Rotation, float Damage, float Strength, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.AddDamageAndImpulse // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	struct FVector GetRotatedImpulseVector(struct FVector Vector, struct FVector Start, struct FVector Target, float Variation, bool UseCustomYaw, float CustomYaw, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.GetRotatedImpulseVector // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1a35c70
	void GetDestructibleDamageValue(struct APawn* Player, enum class E_DestructibleImpactIntensity DestructibleImpactIntesity, struct UObject* __WorldContext, float Damage, float Strength); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.GetDestructibleDamageValue // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ApplyExposed(struct AActor* ReceivingActor, struct AController* Instigator, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ApplyExposed // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void IgniteSkillFinished(struct AActor* Actor, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.IgniteSkillFinished // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ImmobilizeSkillFinished(struct AActor* Actor, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ImmobilizeSkillFinished // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ApplyWeakness(struct AActor* ReceivingActor, float CustomDuration, struct AController* Instigator, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ApplyWeakness // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void BlockReactions(bool bLock, bool IsBlocked, struct AActor* Caster, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.BlockReactions // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	bool UseSidearmWeaponSlot(struct AMadBaseCharacter* character, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.UseSidearmWeaponSlot // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1a35c70
	void Mark ForAnomalystHeal(struct AActor* Instigator, struct AActor* Target, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.Mark ForAnomalystHeal // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void IsCaptain(struct AActor* Enemy, struct UObject* __WorldContext, bool IsCaptain); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.IsCaptain // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ApplyAsh(struct AActor* ReceivingActor, float CustomDuration, struct AController* Instigator, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ApplyAsh // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ApplyShield(struct APawn* Player, float Value, bool IsPercentValue, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ApplyShield // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ApplyHeal(struct APawn* Causer, struct APawn* Target, float Value, bool IsPercentValue, bool ShowCue, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ApplyHeal // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void UpdateThreatLvLPerSkill(struct FName SkillName, struct AActor* Player, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.UpdateThreatLvLPerSkill // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ApplyFreeze(struct AActor* ReceivingActor, struct AController* InstigatorController, float BaseDuration, struct UGameplayEffect* FreezePlayerOverride, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ApplyFreeze // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void RemoveWeaponModChanceBuffFromItem(struct AMadBaseCharacter* MadBaseChar, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.RemoveWeaponModChanceBuffFromItem // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ApplyPoison(struct AActor* ReceivingActor, struct AController* DamageInstigator, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ApplyPoison // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ApplyDisease(struct AActor* ReceivingActor, struct AController* DamageInstigator, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ApplyDisease // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ApplyBleeding(struct AActor* ReceivingActor, struct AController* DamageInstigator, int32_t Stacks, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ApplyBleeding // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void IsBoss(struct AActor* character, struct UObject* __WorldContext, bool Boss); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.IsBoss // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ArmorModTriggeredEffect(struct AMadBaseCharacter* Player, struct AMadBaseCharacter* Instigator, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ArmorModTriggeredEffect // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ArmorModGuaranteedMod(struct AActor* Actor, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ArmorModGuaranteedMod // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ApplyFire(struct AActor* Player, struct AActor* Victim, bool Boss, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ApplyFire // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void WeaponModChanceProcedure(struct UCurveTable* CurveTable, struct FName RowName, struct AActor* Player, struct UObject* __WorldContext, bool ShouldProc); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.WeaponModChanceProcedure // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void CheckArmorModChance(float BaseChance, struct AActor* Player, struct UObject* __WorldContext, bool Triggered); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.CheckArmorModChance // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1a35c70
	void HandleCastingAnim(bool Start, bool HandleCover, struct AMadPlayerCharacter* Caster, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.HandleCastingAnim // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ShowWeapon(struct AMadPlayerCharacter* PlayerCharacter, bool Show, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ShowWeapon // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void RemoveNegativeStatuses(struct AActor* Actor, struct UObject* __WorldContext, int32_t NumberOfEffectsRemoved); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.RemoveNegativeStatuses // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	bool CheckSkillInSlot(struct AMadPlayerCharacter* PlayerCharacter, enum class EMadnessActiveSkillSlots InSlot, struct UObject* SkillDataAsset, struct UObject* __WorldContext); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.CheckSkillInSlot // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
	void ActorHasGameplayTag(struct AActor* Actor, struct FGameplayTag GameplayTag, struct UObject* __WorldContext, bool HasTag); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.ActorHasGameplayTag // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x1a35c70
	void GetStateForWeaponEnhancement(enum class E_WeaponEnhancementMods ModName, struct AActor* MadPlayerCharacter, struct UObject* __WorldContext, bool HasTag); // Function MadnessGameplayAbilityFunctionLibrary.MadnessGameplayAbilityFunctionLibrary_C.GetStateForWeaponEnhancement // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x1a35c70
};

